default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flix_app_development

test:
  <<: *default
  database: flix_app_test

production:
  <<: *default
  database: flix_app_production
